services:
  dev:
    build:
      dockerfile: Dockerfile
    image: ghcr.io/yingchaoorg/local_docs-laravel-cn-docs:10.x
    privileged: false
    container_name: local_docs-laravel-10.x-cn-docs
    volumes:
      - .:/usr/share/nginx/html
    tty: true
    ports:
      - 34809:80